services:
  app:
    build: .
    command: [
    "poetry", "run",
    "uvicorn",
    "app.main:app",
    "--host", "0.0.0.0",
    "--port", "80"
    ]

    ports:
      - "80:80"
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
